export enum PlanningInterest {
  ART = 'ART',
  GASTRONOMY = 'GASTRONOMY',
  SPORTS = 'SPORTS',
  ARCHITECTURE = 'ARCHITECTURE',
  OUTDOOR = 'OUTDOOR',
  MUSIC = 'MUSIC',
  GEEK_CULTURE = 'GEEK_CULTURE',
  LOCAL_HISTORY = 'LOCAL_HISTORY',
  NATURE = 'NATURE',
}
